const ROUTES = {
  ROOT: '/',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  HOME: 'Home',
  SUBSCRIPTION: 'Subscription',
  MENU: 'Menu',
  MAIN_TABS: 'MainTabs',
  SEARCH: 'Search',
  OTP: 'Otp',
  PHONE_NUMBER: 'Phone',
  PROFILE_COMPLETION: 'ProfileCompletion',
  RIDECONFIRMATION: 'RideConfirmation',
  BOOKCONFIMRAITON: 'BookConfirmation',
  UPDATEPROFILE: 'UpdateProfile',
  BOOKINGS: 'Bookings',
  INVOICE: 'Invoice',
  SAVED_ADDRESSES: 'SavedAddresses',
  ADD_EDIT_ADDRESS: 'AddEditAddress',
  WALLET: 'Wallet',
  ADD_MONEY: 'AddMoney',
  TRANSACTION_HISTORY: 'TransactionHistory',
  RATING: 'Rating',
  REVIEWS: 'Reviews',
  NOTIFICATIONS: 'Notifications',
  HELP_SUPPORT: 'HelpSupport',
  FAQ: 'FAQ',
  RAISE_TICKET: 'RaiseTicket',
  TERMS_CONDITIONS: 'TermsConditions',
  PRIVACY_POLICY: 'PrivacyPolicy',
  CANCELLATION_POLICY: 'CancellationPolicy',
  KYC_VERIFICATION: 'KYCVerification',
  PROMO_CODES: 'PromoCodes',
  DAMAGE_REPORT: 'DamageReport',
  RIDE_HISTORY: 'RideHistory',
  PROFILE_EDIT: 'ProfileEdit',
  EXTEND_BOOKING: 'ExtendBooking',
  REFUND_POLICY: 'RefundPolicy',
} as const;

export default ROUTES;
